/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_sssm_jt_raw_socket_JtAbstractSocket */

#ifndef _Included_de_sssm_jt_raw_socket_JtAbstractSocket
#define _Included_de_sssm_jt_raw_socket_JtAbstractSocket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_sssm_jt_raw_socket_JtAbstractSocket
 * Method:    _sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_sssm_jt_raw_socket_JtAbstractSocket__1sayHello
  (JNIEnv *, jobject);

/*
 * Class:     de_sssm_jt_raw_socket_JtAbstractSocket
 * Method:    _open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_sssm_jt_raw_socket_JtAbstractSocket__1open
  (JNIEnv *, jobject);

/*
 * Class:     de_sssm_jt_raw_socket_JtAbstractSocket
 * Method:    _close
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_sssm_jt_raw_socket_JtAbstractSocket__1close
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
