/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_sssm_jt_raw_socket_JtDatagramSocket */

#ifndef _Included_de_sssm_jt_raw_socket_JtDatagramSocket
#define _Included_de_sssm_jt_raw_socket_JtDatagramSocket
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_sssm_jt_raw_socket_JtDatagramSocket
 * Method:    _open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_de_sssm_jt_raw_socket_JtDatagramSocket__1open
  (JNIEnv *, jobject);

/*
 * Class:     de_sssm_jt_raw_socket_JtDatagramSocket
 * Method:    _recvfrom
 * Signature: (I)Lde/sssm/jt/raw/socket/JtDatagramPacket;
 */
JNIEXPORT jobject JNICALL Java_de_sssm_jt_raw_socket_JtDatagramSocket__1recvfrom
  (JNIEnv *, jobject, jint);

/*
 * Class:     de_sssm_jt_raw_socket_JtDatagramSocket
 * Method:    _sendto
 * Signature: (ILjava/lang/String;I[B)V
 */
JNIEXPORT void JNICALL Java_de_sssm_jt_raw_socket_JtDatagramSocket__1sendto
  (JNIEnv *, jobject, jint, jstring, jint, jbyteArray);

/*
 * Class:     de_sssm_jt_raw_socket_JtDatagramSocket
 * Method:    _setTtl
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_sssm_jt_raw_socket_JtDatagramSocket__1setTtl
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
